# Generated by Django 3.1.2 on 2020-10-04 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import src.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_auto_20201004_0445'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLibraryBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('lending', 'lending'), ('returned', 'returned')], max_length=16)),
                ('lended_dt', models.DateTimeField(blank=True, null=True)),
                ('deadline_dt', models.DateTimeField(blank=True, null=True)),
                ('library_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraries.librarybook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user library book',
                'verbose_name_plural': 'user library books',
            },
            bases=(models.Model, src.utils.models.TimeStampedModelMixin),
        ),
    ]
